# ####################
# # AFK Signs config #
# ####################
#
# afk-time : Time for a player to be marked as AFK (in minutes)
#
# save-message : Save player's messages on exit
#
# use-notification is to allow plugin to query if new updates are available $Not Implemented$

afk-time: 5
save-message: true
use-notification: true