main: com.gmail.chloepika.plugins.afksigns.AFKSigns
name: AFK Signs
version: 1.2
author: Chloe-chan
description: A plugin that handles AFK players.

commands:
  afk:
    description: Commands that alters how the plugin handles AFK players.
    usage: /AFK help <- Help page
    aliases: afksign